//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuocPhi
    {
        public int MaCuocPhi { get; set; }
        public string TenKhuVuc { get; set; }
        public Nullable<decimal> DonGia { get; set; }
    }
}
